=== sanaaftab/stendhal_S1Team21/data/conf/achievements.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
	xmlns:Q1="stendhal">

	<element name="achievements" type="Q1:achievementGroup"></element>

	<complexType name="achievementGroup">
		<sequence>
			<element name="achievement" type="Q1:achievementType" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="achievementType">
		<sequence>
			<element name="implementation" type="string"></element>
			<element name="identifier" type="string"></element>
			<element name="title" type="string"></element>
			<element name="description" type="string"></element>
			<element name="baseScore" type="int"></element>
			<element name="category" type="string"></element>
			<element name="active" type="boolean"></element>
			<element name="condition" type="string"></element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>
	

</schema>

=== sanaaftab/stendhal_S1Team21/data/conf/achievements/experience.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../achievements.xsd ">

	<achievement name="OMG">
		<implementation class-name="games.stendhal.server.core.rp.achievement.factory.ExperienceAchievementFactory" />
		<category value="EXPERIENCE"/>
		<attributes>
			<identifier value="xp.level.5" />
			<title value="OMG" />
			<description value="Reach level 5" />
			<baseScore value="1" />
			<active value="true" />
			<condition class-name="games.stendhal.server.entity.npc.condition.LevelGreaterThanCondition" />
			<parameter value="4"/>
		</attributes>
	</achievement>

</achievements>
